Support Swift5.4
krzysztofzablocki/Sourcery pull request #947
Opened 2021-04-27 23:15 UTC by funzin

2021-04-27 23:55 UTC, funzin commented
Circle CI has not  supported Xcode12.5 yet🤦‍♂️
![スクリーンショット 2021-04-28 8 53 11](https://user-images.githubusercontent.com/12893657/116326356-34d7f780-a7ff-11eb-8da6-0cba89c293b5.png)

2021-04-28 04:29 UTC, krzysztofzablocki requested changes
Sourcery works on new Xcode if you use binary distribution.

This is useful for updating to newer version but you need to update bundled dylib, that's what we rely on because we rewrite rpath, we are not relying on user Xcode version

2021-04-28 04:55 UTC, funzin commented
>Sourcery works on new Xcode if you use binary distribution.

I installed Sourcery via SwiftPackageManager or Mint, not use binary distribution.

2021-04-28 05:38 UTC, krzysztofzablocki commented
@funzin I'm happy with the PR but you just need to copy the dylib from new Xcode and put it in the repo as we bundle it, once we move to SPM branch it will be using right dylib bundling regardless of Xcode version too

2021-04-28 06:57 UTC, funzin commented
I understood.

I should only replace [lib_InternalSwiftSyntaxParser.dylib](https://github.com/krzysztofzablocki/Sourcery/blob/master/lib_InternalSwiftSyntaxParser.dylib) in the repo to new dylib which Xcode12.5 has, right?

2021-04-28 07:02 UTC, krzysztofzablocki commented
no no, this PR is good, you just need to replace that file and update `changelog.md` then I can merge :)

2021-04-28 08:31 UTC, funzin commented
- Replaced `lib_InternalSwiftSyntaxParser` f1def25
- Updated ChangeLog dc1de30
  - Current version is `1.4.1` so I added `1.4.2` section

2021-05-01 01:57 UTC, funzin commented
Failed test...

2021-05-01 08:01 UTC, closed without merging